/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AudienceSection: typeof import('./components/sections/AudienceSection.vue')['default']
    CallToAction: typeof import('./components/sections/CallToAction.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/sections/HeroSection.vue')['default']
    ProblemSection: typeof import('./components/sections/ProblemSection.vue')['default']
    ProcessSection: typeof import('./components/sections/ProcessSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./components/sections/ServicesSection.vue')['default']
    SolutionSection: typeof import('./components/sections/SolutionSection.vue')['default']
    WhyUsSection: typeof import('./components/sections/WhyUsSection.vue')['default']
  }
}
